# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [3]:
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = 12742
x= "The diameter of {} is {} kilometers "
print(x.format(planet,diameter))

The diameter of Earth is 12742 kilometers 


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
import numpy as np
arr1 = np.array([0,0,0,0,0,0,0,0,0,0])
print(arr1)

[0 0 0 0 0 0 0 0 0 0]


In [12]:
import numpy as np
arr2 = np.array([5,5,5,5,5,5,5,5,5,5])
print(arr2)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
arr3 = np.arange(20,35,2)
print(arr3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
import numpy as np
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [22]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [3]:
import pandas as pd
data = { "day":["Monday","Tuesday","Wednesday"],
         "month":["October","November","December"] 
       }
df= pd.Dataframe(data)
print(df)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
import pandas as pd


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]